{% set name = "linetools" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2792647c4451b9d0f83e9d6cf09b59292ad8d97168d366be7d9496094c7c5d2

build:
  noarch: python
  number: 0
  entry_points:
    - lt_absline = linetools.scripts.lt_absline:main
    - lt_line = linetools.scripts.lt_line:main
    - lt_xabssys = linetools.scripts.lt_xabssys:main
    - lt_xspec = linetools.scripts.lt_xspec:main
    - lt_continuumfit = linetools.scripts.lt_continuumfit:main
    - lt_plot = linetools.scripts.lt_plot:main
    - lt_radec = linetools.scripts.lt_radec:main
    - lt_solabnd = linetools.scripts.lt_solabnd:main
    - lt_get_COS_LP = linetools.scripts.lt_get_COS_LP:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=5
  run:
    - python >=3.8
    - numpy >=1.20.0
    - astropy >=5.2.1
    - scipy >=1.6
    - h5py >=3.7
    - matplotlib-base >=3.3
    - pyyaml >=5.1
    - ipython >=7.10.0
    - qtpy >=1.9

test:
  imports:
    - linetools
    - linetools.abund
    - linetools.analysis
    - linetools.guis
    - linetools.isgm
    - linetools.lists
    - linetools.scripts
    - linetools.spectra
  commands:
    - lt_absline --help
    - lt_line --help
    - lt_xabssys --help
    - lt_xspec --help
    - lt_continuumfit --help
    - lt_plot --help
    - lt_radec --help
    - lt_solabnd --help
    - lt_get_COS_LP --help

about:
  home: http://linetools.readthedocs.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A package for analysing absorption and emission lines in 1d spectra, especially galaxy and quasar spectra.
  doc_url: http://linetools.readthedocs.org/
  dev_url: https://github.com/linetools/linetools

extra:
  recipe-maintainers:
    - mwcraig
    - profxj
