{% set name = "linetools" %}
{% set version = "0.3.dev2206" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31c353a20aa8567aee57d19804557e34292ecc9f3d250c92f40495866c387a36
  patches:
    - setup.cfg.patch

build:
  number: 1
  entry_points:
    - lt_absline = linetools.scripts.lt_absline:main
    - lt_line = linetools.scripts.lt_line:main
    - lt_xabssys = linetools.scripts.lt_xabssys:main
    - lt_xspec = linetools.scripts.lt_xspec:main
    - lt_continuumfit = linetools.scripts.lt_continuumfit:main
    - lt_plot = linetools.scripts.lt_plot:main
    - lt_radec = linetools.scripts.lt_radec:main
    - lt_solabnd = linetools.scripts.lt_solabnd:main
    - lt_get_COS_LP = linetools.scripts.lt_get_COS_LP:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - astropy
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib-base
    - pyqt
    - h5py

test:
  imports:
    - linetools
    - linetools.abund
    - linetools.analysis
    - linetools.guis
    - linetools.isgm
    - linetools.lists
    - linetools.scripts
    - linetools.spectra
  commands:
    - lt_absline --help
    - lt_line --help
    - lt_xabssys --help
    - lt_xspec --help
    - lt_continuumfit --help
    - lt_plot --help
    - lt_radec --help
    - lt_solabnd --help
    - lt_get_COS_LP --help

about:
  home: http://linetools.readthedocs.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A package for analysing absorption and emission lines in 1d spectra, especially galaxy and quasar spectra.
  doc_url: http://linetools.readthedocs.org/
  dev_url: https://github.com/linetools/linetools

extra:
  recipe-maintainers:
    - mwcraig
    - profxj
