travis:
  secure:
    BINSTAR_TOKEN: ZoS1Mzffn7e/ZH/fuZ3Pt5auwDWFlbbPm0Xt3eN5SPki43humdJ4P+6u9N5XS3ZsTlfPz7wwowNvc3HLWdjDkwPihk4qjTWNubFL0+4FPGnvVPS3OwUIFET7+eEFyFY98IwgpTj/zE2WL8q74Vy8hSsgKLH0WI53y1fHbxoZSchZBZe0vnGbyR6wIGn3rQ1uNCILgbMXwmvB2pdJpBX9vIIp57MBJPFfynx3X5uIO03Gji8BOeIYgezPghXcZZJFlR6CM90pFBwXiM7TRNGqyy2SCc3br7IzAY1hnbfY6sTKmZ2U8lMhRA5cgYkBwxU4f/2bvDnpoL4R2zblQOYAgY6hYAnCmQHWCYYMUTgjGplf/+hKQvMcSSTrQE/9CQDX4j83rwzP0SfJAaYM8XhQnsy0hY4/Fvv8xQefBsNsM9vY/uPMppQ0HeQVQXCO2Ix8CzffzmAR0ROZgO38GpVK8emFQLMjf46Bpxg/c8VcD/IqKgT8Z22u3gGECOd8dge6CPhL0WlFTG4qq5ktNWa7l279BCX09MlKYluLbxkcVTNkdek/+HjyddWt6vXFLwaHklEnvkogVhaMaIFrcxfXBikDJrmVorO6aB4c0nmpUCVyLhwNRLVjByyw9LLOu9aV5p83c+4uEwloKArsWBuqf7W558GestYl3gZy8zLR0jk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
